"""Internal transactional ports; neither SQL nor Provider types cross this boundary."""

from collections.abc import Callable, Iterable
from dataclasses import dataclass
from typing import Protocol

from jobhunter.domain.invocation.models import (
    Admission,
    Descriptor,
    LocalRead,
    ModelRead,
    Reconciliation,
    Response,
    Run,
)


class Repository(Protocol):
    def run(self, run_id: str) -> Run: ...
    def open_runs(self) -> list[Run]: ...
    def insert_run(self, run: Run) -> None: ...
    def save_run(self, run: Run) -> None: ...
    def model(self, invocation_id: str) -> ModelRead: ...
    def models(self, run_id: str) -> list[ModelRead]: ...
    def insert_model(self, model: ModelRead) -> None: ...
    def save_model(self, model: ModelRead) -> None: ...
    def response(self, invocation_id: str) -> Response: ...
    def insert_response(self, response: Response) -> None: ...
    def tools(self, run_id: str) -> list[LocalRead]: ...
    def tool(self, invocation_id: str) -> LocalRead: ...
    def insert_tool(self, tool: LocalRead) -> None: ...
    def save_tool(self, tool: LocalRead) -> None: ...
    def proof_complete(self, run_id: str) -> bool: ...
    def complete_proof(self, run_id: str) -> None: ...


class Persistence(Protocol):
    def transact[T](self, operation: Callable[[Repository], T], *, write: bool = False) -> T: ...
    def check_owner(self) -> None: ...
    def claim_runtime(self) -> None: ...


class Consumer(Protocol):
    key: str
    max_models: int
    max_tools: int

    def reconcile_result(self, repo: Repository, run: Run) -> Reconciliation: ...
    def admit_recovery(self, repo: Repository, run: Run, now: str) -> Admission: ...
    def resume_local(self, repo: Repository, run: Run) -> None: ...


class ResponseFormat(Protocol):
    key: str

    def validate(self, payload: bytes) -> None: ...


class Clock(Protocol):
    def utc(self) -> str: ...
    def monotonic(self) -> float: ...


@dataclass(frozen=True, repr=False)
class Frame:
    data: bytes
    terminal: bool


class Gateway(Protocol):
    """Exactly one call, finite frames; adapters may not retry or fall back."""

    def receive(self, descriptor: Descriptor, receive_limit: int) -> Iterable[Frame]: ...
    def interrupt(self) -> None: ...
